CREATE TABLE BARANG 
   (	"ID_BARANG" NUMBER(11,0) NOT NULL ENABLE, 
	"KODE_BARANG" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NAMA_BARANG" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"HARGA" NUMBER(11,0)